version: "3.7"
services:

  postgres:
    image: postgres:12
    restart: always
    ports:
      - "54321:5432"
    volumes:
      - postgres-cerebro:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cerebro"
      PGDATA: "/var/lib/postgresql/data/pgdata"

volumes:
  postgres-cerebro:
    driver: local
